### ISSUE TITLE
Is there any request rate limiting functionality?

### ISSUE THREAD

**Issue by xfnty** [leonardodalinky/pywmapi#8]
Hi, I'm sorry if I'm being inattentive, but I did not see any request rate limiting functionality, when Warframe Market's ToS caps it [below 3 requests per second](https://warframe.market/tos).

I'm not sure if it's an intentional design choise, but I would be pleased if the library did rate limiting for me.

I used [requests-ratelimiter](https://pypi.org/project/requests-ratelimiter) in [my script](https://github.com/xfnty/update-orders/blob/main/update-orders.py#L16) which replaces `requests` library with basically zero effort required.

So am I missing something here?

**Comment by leonardodalinky** [comment]
Interesting. I always suppose that users should take the responsibility for the limit of ToS since the APIs should be **stateless**. 

Though it is relatively easy to apply rate-limiters to the existing APIs, there would be *invisible* stateful counting to control the request rate. And I think it is a bad design.

Anyway, I would consider adding a process-level rate-limiters in the near future update. And anyone who needs this can add an optional argument in every API function call. Thank you for suggestions.
